traxeda/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='user/', permanent=False), name='index')
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('', views.homepage, name="homepage"),
    path('register', views.register, name="register"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),
    path('createpost', views.create_post, name="createpost"),
    path('viewposts', views.PostsView.as_view(), name="viewposts")
]

products/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=100)
    weight = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=9, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        app_label = 'products'

user/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def create_post(request, text):
        user = request.user
        post = Post(created_by=user, text=text)
        post.save()
        return post

    class Meta:
        app_label = 'user'

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from . import models

class Registration(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=40)
    last_name = forms.CharField(max_length=40)

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "username", "password1", "password2")

    def save(self, commit=True):
        user = super(Registration, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        
        if commit:
            user.save()
        return user


class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ('text',)

products/views.py
from django.shortcuts import render

# Create your views here.

user/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .forms import Registration, CreatePost
from django.contrib.auth import login as login_user, authenticate, logout as logout_user
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView

from . import models
# Create your views here.


def register(request):
    if request.method == "POST":
        form = Registration(request.POST)
        if form.is_valid():
            user = form.save()
            login_user(request, user)
            messages.success(request, "Registration succesful")
            return redirect('user:homepage')
        messages.error(request, "Unsuccesssful registration. Invalid information.")
    form = Registration()
    return render(request=request, template_name='user/register.html', context={'register_form': form})    

def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login_user(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                if redirect_url := request.GET.get('next'):
                    return redirect(redirect_url)
                else:
                    return redirect("user:homepage")
            else:
                messages.error(request, "invalid username or password.")

        else:
            messages.error(request, "Invalid username or password.")

    form = AuthenticationForm()
    return render(request=request, template_name='user/login.html', context={'login_form': form})

def logout(request):
    logout_user(request)
    messages.info(request, "You have succesfully logged out.")
    return redirect("user:homepage")

@login_required(login_url=reverse_lazy('user:login'))
def create_post(request):
    if request.method == "POST":
        form = CreatePost(request.POST)
        if form.is_valid():
            text = form.cleaned_data.get('text')
            post = models.Post.create_post(request, text)
            if post:
                messages.info(request, f"Created new post.")
                return redirect('user:viewposts')
            else:
                messages.error(request, f"Could not create a post.")
        else:
            messages.error(request, f"Could not create a post.")
    else:
        form = CreatePost()
        return render(request=request, template_name='user/create_post.html', context={'post_form':form})      

class PostsView(ListView):
    model = models.Post

def homepage(request):
    return render(request=request, template_name='user/homepage.html')

templates/root.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Traxeda</title>
</head>
<header class="bg-gray-600 p-3">
<h1 class="font-bold text-gray-300 text-2xl"><a class="hover:text-gray-200" href="{% url 'user:homepage' %}">Traxeda</a></h1>
</header>
<body class="bg-gray-50 text-gray-800">
    {% block content %}
    {% endblock content %}
</body>
</html>

user/templates/user/create_post.html
{% extends 'root.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% if message %}
<ul class="border bg-gray-200 font-bold p-3">
  {% for message in messages %}
  <li class="text-gray-600">{{message}}</li>
  {% endfor %}
</ul>
{% endif %}
<section class="w-1/2 p-8 bg-gray-200 m-4 shadow-md">
  <h3 class="font-bold mb-3 text-gray-600 text-2xl">Create Post</h3>
  <form method="POST" class="space-y-3">
  {% csrf_token %}
  {{ post_form|crispy }}
  <button class="btn btn-primary" type="submit">Create</button>
  </form>
</section>
{% endblock content %}

user/templates/user/homepage.html
{% extends 'root.html' %}
{% block content %}
{% if message %}
<ul class="border bg-gray-200 font-bold p-3">
  {% for message in messages %}
  <li class="text-gray-600">{{message}}</li>
  {% endfor %}
</ul>
{% endif %}
<section class="p-4">
<div class='bg-gray-200 p-3 shadow-md font-semibold mb-3'>
<h3 class="font-bold mb-3 text-gray-600 text-2xl">Authentication</h3>
{% if not user.is_authenticated %}
<a class="font-mono text-blue-500" href="{% url 'user:register' %}">Registration</a><br>
<a class="font-mono text-blue-500" href="{% url 'user:login' %}">Login</a>
{% else %}
<p>Current User - {{user.username}} | <a class="font-mono text-blue-500" href="{% url 'user:logout' %}">Logout</a></p>
{% endif %}
</div>
<div class='bg-gray-200 p-3 shadow-md font-semibold'>
<h3 class="font-bold mb-3 text-gray-600 text-2xl">Actions</h3>
{% if user.is_authenticated %}
<a class="font-mono text-blue-500" href="{% url 'user:createpost' %}">Create Post</a><br>
{% endif %}
<a class="font-mono text-blue-500" href="{% url 'user:viewposts' %}">View Posts</a>
</div>

</section>

{% endblock content %}

user/templates/user/login.html
{% extends 'root.html' %} {% block content %}
{% load crispy_forms_tags %}
{% if messages %}
<ul class="border bg-gray-200 font-bold p-3">
  {% for message in messages %}
  <li class="text-gray-600">{{message}}</li>
  {% endfor %}
</ul>
{% endif %}
<section class="w-1/2 p-8 bg-gray-200 m-4 shadow-md">
  <h3 class="font-bold mb-3 text-gray-600 text-2xl">Login</h3>
  <form method="POST" class="space-y-3">
  {% csrf_token %}
  {{ login_form|crispy }}
  <button class="btn btn-primary" type="submit">Login</button>
  </form>
<p class="mt-3">Don't have an account? <a class="hover:text-blue-600 font-semibold text-blue-400" href="{% url 'user:register' %}">Create an account.</a></p>
</section>
{% endblock content %}

user/templates/user/post_list.html
{% extends 'root.html' %}
{% block content %}
<section class="p-3 space-y-3 w-1/2">
<h3 class="font-bold mb-3 text-gray-600 text-2xl">Posts</h3>
{% for post in object_list %}
<div class="bg-gray-200 shadow-md">
<div class="p-2 space-y-1">
<p class="font-bold text-sm text-blue-600">{{post.created_by}}</p>
<p class="px-2">{{post.text}}</p>
</div>
<div class="bg-gray-300 p-2">
    <small><span class="font-semibold">Created :</span>{{post.created_at}}</small>
    |
    <small><span class="font-semibold" >Updated :</span>{{post.updated_at}}</small>
</div>
</div>
{% endfor %}
</section>
{% endblock content %}

user/templates/user/register.html
{% extends 'root.html' %} 
{% load crispy_forms_tags %}
{% block content %}
{% if message %}
<ul class="border bg-gray-200 font-bold p-3">
  {% for message in messages %}
  <li class="text-gray-600">{{message}}</li>
  {% endfor %}
</ul>
{% endif %}
<section class="w-1/2 p-8 bg-gray-200 m-4 shadow-md">
  <h3 class="font-bold mb-3 text-gray-600 text-2xl">Sign up</h3>
  <form method="POST" class="space-y-3">
    {% csrf_token %} {{ register_form|crispy }}
    <button class="btn btn-primary" type="submit">Register</button>
  </form>
  <p class="mt-2">
    If you already have an account,
    <a href="{% url 'user:login' %}" class="hover:text-blue-600 font-semibold text-blue-400">Login</a> instead.
  </p>
</section>
{% endblock content %}